apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: ameercohyve/customer:latest
        ports:
        - containerPort: 8001
        env:
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: APP_SECRET
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGODB_URI_CUSTOMER
        - name: MSG_QUEUE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MSG_QUEUE_URL
        - name: EXCHANGE_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: EXCHANGE_NAME
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: PORT_CUSTOMER
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  type: ClusterIP
