apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: <DOCKER_REGISTRY>/products:${GITHUB_SHA}
        ports:
        - containerPort: 8002
        env:
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: products-secrets
              key: APP_SECRET
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: products-secrets
              key: MONGODB_URI
        - name: MSG_QUEUE_URL
          valueFrom:
            secretKeyRef:
              name: products-secrets
              key: MSG_QUEUE_URL
        - name: EXCHANGE_NAME
          value: ONLINE_STORE
        - name: PORT
          value: "8002"
---
apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  selector:
    app: products
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8002
  type: ClusterIP
