# Template for Kubernetes secrets for all services
# Replace <base64-encoded-value> with actual base64-encoded secret values
---
apiVersion: v1
kind: Secret
metadata:
  name: customer-secrets
  namespace: default
stringData:
  APP_SECRET: <base64-encoded-value>
  MONGODB_URI: <base64-encoded-value>
  MSG_QUEUE_URL: <base64-encoded-value>
---
apiVersion: v1
kind: Secret
metadata:
  name: products-secrets
  namespace: default
stringData:
  APP_SECRET: <base64-encoded-value>
  MONGODB_URI: <base64-encoded-value>
  MSG_QUEUE_URL: <base64-encoded-value>
---
apiVersion: v1
kind: Secret
metadata:
  name: shopping-secrets
  namespace: default
stringData:
  APP_SECRET: <base64-encoded-value>
  MONGODB_URI: <base64-encoded-value>
  MSG_QUEUE_URL: <base64-encoded-value>
