apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
      - name: shopping
        image: ameercohyve/shopping:latest
        ports:
        - containerPort: 8003
        env:
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: APP_SECRET
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGODB_URI_SHOPPING
        - name: MSG_QUEUE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MSG_QUEUE_URL
        - name: EXCHANGE_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: EXCHANGE_NAME
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: PORT_SHOPPING
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-service
spec:
  selector:
    app: shopping
  ports:
  - protocol: TCP
    port: 8003
    targetPort: 8003
  type: ClusterIP
