name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAMESPACE: ameercohyve

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [customer, products, shopping, proxy]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ./nodejs_microservice/${{ matrix.service }}
          file: ./nodejs_microservice/${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ matrix.service }}:latest

  deploy:
    needs: build-test-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name microservices

      - name: Deploy to EKS
        run: |
          kubectl apply -f nodejs_microservice/k8s/secrets.yaml
          kubectl apply -f nodejs_microservice/k8s/customer-deployment.yaml
          kubectl apply -f nodejs_microservice/k8s/products-deployment.yaml
          kubectl apply -f nodejs_microservice/k8s/shopping-deployment.yaml
          kubectl apply -f nodejs_microservice/k8s/proxy-deployment.yaml
